### ISSUE TITLE
 undefined is not a function

### ISSUE THREAD

**Issue by kevin1193** [omouse/grunt2gulp.js#18]
I have encounter this issue after installing jit-grunt. Kindly help. 

 TypeError: undefined is not a function
    at factory (/var/www/workspace/grunt2gulp.js/node_modules/jit-grunt/lib/jit-grunt.js:135:29)
    at module.exports (/var/www/workspace/grunt2gulp.js/node_modules/jit-grunt/jit-grunt.js:6:13)
    at module.exports (/var/www/workspace/grunt2gulp.js/Gruntfile.js:13:23)
    at convertGruntFile (/var/www/workspace/grunt2gulp.js/bin/grunt2gulp.js:505:3)
    at Object.<anonymous> (/var/www/workspace/grunt2gulp.js/bin/grunt2gulp.js:517:7)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

**Comment by omouse** [comment]
How did you run grunt2gulp and could you provide the Gruntfile that you
were running it with?

**Comment by ptdv** [comment]
I ran into the same issue on a Windows 10 box:
```
./grunt2gulp.js ../../Gruntfile.js > gulpfile.js
D:\dev\web-status\grunt2gulp.js\bin\grunt2gulp.js:534
        throw e;
              ^
TypeError: undefined is not a function
    at module.exports (D:\dev\web-status\Gruntfile.js:347:11)
    at convertGruntFile (D:\dev\web-status\grunt2gulp.js\bin\grunt2gulp.js:505:3)
    at Object.<anonymous> (D:\dev\web-status\grunt2gulp.js\bin\grunt2gulp.js:517:7)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by omouse** [comment]
@ptdv can you provide the whole or a partial part of the Gruntfile.js you're trying to convert?
