### ISSUE TITLE
Cannot read property 'header' of undefined

### ISSUE THREAD

**Issue by milieu** [omouse/grunt2gulp.js#2]
```zsh
 ~/me/project/ [gulpify] node grunt2gulp.js Gruntfile.js

/Users/mere/me/project/node_modules/time-grunt/node_modules/hooker/lib/hooker.js:64
      if (toString.call(obj[props[i]]) !== "[object Function]" ||
                           ^
TypeError: Cannot read property 'header' of undefined
    at forMethods (/Users/mere/me/project/node_modules/time-grunt/node_modules/hooker/lib/hooker.js:64:28)
    at Object.exports.hook (/Users/mere/me/project/node_modules/time-grunt/node_modules/hooker/lib/hooker.js:89:12)
    at module.exports (/Users/mere/me/project/node_modules/time-grunt/time-grunt.js:47:9)
    at module.exports (/Users/mere/me/project/Gruntfile.js:19:24)
    at convertGruntFile (/Users/mere/me/project/grunt2gulp.js:243:3)
    at Object.<anonymous> (/Users/mere/me/project/grunt2gulp.js:252:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

[Gruntfile.js in question](https://gist.github.com/milieu/1f4e765083e5339e9e2f). Originally generated via [yo](http://yeoman.io/)

**Comment by omouse** [comment]
@milieu are other gruntfiles generated by yeoman failing to convert?

**Comment by andela-bolanrewaju** [comment]
Same here, got the same error. Dunno why it won't load installed modules

<pre>
Error: Cannot find module 'load-grunt-tasks'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
</pre>

**Comment by omouse** [comment]
@milieu The issue is that the gruntConverter is passed to the module.exports function, it implements the same interface as grunt does, however it doesn't currently implement the `header` property. Working on a fix right now.

@andela-bolanrewaju you have to do an `npm install` and install the modules unless there's some other issue, what I see there is that you need to install the `load-grunt-tasks` module.

**Comment by omouse** [comment]
there's a new issue now with the file but at least the log object is defined.

**Comment by omouse** [comment]
ALSO **very important:** when you run the file through grunt2gulp, it produces a LOT of duplicate tasks.
