### ISSUE TITLE
Couldn't be used when grunt using registerMultiTask.

### ISSUE THREAD

**Issue by fatkhanfauzi** [omouse/grunt2gulp.js#20]
It couldn't be used when grunt file contain registerMultiTask.

**Comment by omouse** [comment]
could you share how your Gruntfile looks like, at least the lines near the registerMultiTask?

**Comment by fatkhanfauzi** [comment]
Please look at this file:
https://github.com/voidlabs/mosaico/blob/master/tasks/combineKOTemplates.js

I've just tried to use it on that file.

**Comment by omouse** [comment]
That file looks like a Grunt plugin rather than a Gruntfile? Have you tried running grunt2gulp on the Gruntfile rather than the Grunt plugin file?

## Source code of the Gruntfile and plugin

For future reference, the source code of the plugin and the gruntfile from that mosaico project are below:

### combineKOTemplates.js

```js
"use strict";
var path = require('path');

module.exports = function(grunt) {
  grunt.registerMultiTask("combineKOTemplates", function() {
    var files = grunt.file.expand(this.data.src),
        result = "";
 
    var script = this.data.templateSystemPath || '../src/js/bindings/choose-template.js';

    result += "var templateSystem = require('"+script+"');\n";
    result += "document.addEventListener('DOMContentLoaded', function(event) {\n";
    files.forEach(function(file) {
      //strip the extension to determine a template name
      var name = path.basename(file).replace(".tmpl.html", ""),
        //remove line feeds and escape quotes
        escapedContents = grunt.file.read(file).replace(/"/g ,"\\x22").replace(/(\r\n|\n|\r)/gm, "");
        result += "templateSystem.addTemplate(\"" + name + "\", \"" + escapedContents + "\");\n";
    });
    result += "});\n";
 
    grunt.file.write(this.data.dest, result);
  });
};
```

### Gruntfile.js

```js
"use strict";
var path = require('path');

module.exports = function(grunt) {
  require('load-grunt-tasks')(grunt);
  grunt.loadTasks('tasks');

  grunt.initConfig({

    makeThumbs: {
      main: {
        templates: './templates/*/*.html',
        template: './templates/%/*.html',
        outputFolder: 'edres',
        renderWidth: 680,
        outputWidth: 340
      }
    },

    combineKOTemplates: {
      main: {
        src: "src/tmpl/*.tmpl.html",
        dest: "build/templates.js"
      }
    },

    jshint: {
      all: [
        'Gruntfile.js',
        'src/**/*.js',
      ],
      options: {
        reporter: require('jshint-stylish'),
        sub: true,
        jshintrc: true,
        browserify: true

      }
    },

    less: {
      options: {
        sourceMap: true,
        sourceMapRootpath: '../',
        /* sourceMapFilename: 'build/mosaico.css.map' */
        sourceMapFileInline: true
      },
      css: {
        files: {
          "build/mosaico.css": "src/css/app_standalone.less",
          "build/mosaico-material.css": "src/css/app_standalone_material.less"
        }
      }
    },

    postcss: {
      options: {
        map: {
          inline: false /* , prev: 'build/app.css.map' */
        },
        diff: false,
        processors: [
          require('autoprefixer-core')({
            browsers: 'ie 10, last 2 versions'
          }),
          require('csswring')()
        ]
      },
      dist: {
        src: 'build/mosaico.css',
        dest: 'dist/mosaico.min.css'
      },
      material: {
        src: 'build/mosaico-material.css',
        dest: 'dist/mosaico-material.min.css'
      }
    },

    browserify: {
      debug: {
        options: {
          browserifyOptions: {
            standalone: 'Mosaico'
          },
          watch: true,
        },
        files: {
          'build/mosaico.js': ['./src/js/app.js', './build/templates.js']
        }
      },
      main: {
        options: {
          browserifyOptions: {
            debug: true,
            fullPaths: false,
            standalone: 'Mosaico'
          },
          transform: ['uglifyify'],
          watch: true,
        },
        files: {
          'build/mosaico.debug.js': ['./src/js/app.js', './build/templates.js']
        }
      }
    },

    exorcise: {
      main: {
        options: {
          bundleDest: 'dist/mosaico.min.js'
        },
        files: {
          'dist/mosaico.min.js.map': ['build/mosaico.debug.js'],
        }
      }
    },

    watch: {
      css: {
        files: ['src/css/*.less', 'src/**/*.css'],
        tasks: ['less', 'postcss']
      },
      tmpl: {
        files: ['src/tmpl/*.tmpl.html'],
        tasks: ['combineKOTemplates']
      },
      exorcise: {
        files: ['build/mosaico.debug.js'],
        tasks: ['exorcise']
      },
      web: {
        options: {
          livereload: true
        },
        files: ['*.html', 'dist/**/*.js', 'dist/**/*.css'],
      },
      jshint: {
        files: ['src/js/**/*.js'],
        tasks: ['newer:jshint']
      }
    },

    express: {
      dev: {
        options: {
          port: 9006,
          showStack: true,
          hostname: '127.0.0.1',
          open: true,
          bases: ['.'],
          server: 'backend/main.js'
        }
      }
    },

    copy: {
      res: {
        expand: true,
        cwd: 'res',
        src: '**',
        dest: 'dist/'
      }
    },

    bowercopy: {
      libs: {
        options: {
          destPrefix: 'dist/vendor'
        },
        files: {
          'knockout.js': 'knockout/dist/knockout.js',
          'jquery.min.js': 'jquery/dist/jquery.min.js',
          'jquery.min.map': 'jquery/dist/jquery.min.map',
          'jquery-ui.min.js': 'jquery-ui/jquery-ui.min.js',
          'jquery-ui.min.css': 'jquery-ui/themes/smoothness/jquery-ui.min.css',
          'jquery.ui.touch-punch.min.js': 'jqueryui-touch-punch/jquery.ui.touch-punch.min.js',
          'knockout-jqueryui.min.js': 'knockout-jqueryui/dist/knockout-jqueryui.min.js',
          'canvas-to-blob.min.js': 'blueimp-canvas-to-blob/js/canvas-to-blob.min.js',
          'load-image.all.min.js': 'blueimp-load-image/js/load-image.all.min.js',
          'jquery.iframe-transport.js': 'jquery-file-upload/js/jquery.iframe-transport.js',
          'jquery.fileupload.js': 'jquery-file-upload/js/jquery.fileupload.js',
          'jquery.fileupload-process.js': 'jquery-file-upload/js/jquery.fileupload-process.js',
          'jquery.fileupload-image.js': 'jquery-file-upload/js/jquery.fileupload-image.js',
          'jquery.fileupload-validate.js': 'jquery-file-upload/js/jquery.fileupload-validate.js',
          'evol.colorpicker.min.css': 'evol-colorpicker/css/evol.colorpicker.min.css',
          'evol.colorpicker.min.js': 'evol-colorpicker/js/evol.colorpicker.min.js',
          'tinymce.min.js': 'tinymce/tinymce.min.js',
          'themes': 'tinymce/themes',
          'skins': 'tinymce/skins',
          'plugins': 'tinymce/plugins',
          'notoregular': 'webfont-notosans/regular',
        }
      },
      fontawesome: {
        options: {
          destPrefix: 'dist/fa'
        },
        files: {
          'fonts/fontawesome-webfont.woff2': 'font-awesome/fonts/fontawesome-webfont.woff2',
          'fonts/fontawesome-webfont.woff': 'font-awesome/fonts/fontawesome-webfont.woff',
          'fonts/fontawesome-webfont.ttf': 'font-awesome/fonts/fontawesome-webfont.ttf',
          'fonts/fontawesome-webfont.svg': 'font-awesome/fonts/fontawesome-webfont.svg',
          'fonts/fontawesome-webfont.eot': 'font-awesome/fonts/fontawesome-webfont.eot'
        }
      }
    },

    jasmine_node: {
      main: {
        options: {
          coverage: {
            reportDir: 'build/coverage',
          },
          forceExit: false,
          match: '.',
          matchAll: false,
          specFolders: ['spec'],
          extensions: 'js',
          specNameMatcher: 'spec',
          captureExceptions: true,
          junitreport: {
            report: false,
            savePath: './build/jasmine/',
            useDotNotation: true,
            consolidate: true
          }
        },
        src: ['src/**/*.js']
      }
    },

  });

  grunt.registerTask('js', ['combineKOTemplates', 'browserify', 'exorcise']);
  grunt.registerTask('css', ['less', 'postcss']);
  grunt.registerTask('server', ['express', 'watch', 'express-keepalive']);
  grunt.registerTask('build', ['bowercopy', 'copy', 'jshint', 'js', 'css']);
  grunt.registerTask('default', ['build', 'server']);
  grunt.registerTask('test', ['jasmine_node']);
};
```

**Comment by fatkhanfauzi** [comment]
Yes, i've tried to run it on the Gruntfile, but the same issue was appeared.

**Comment by omouse** [comment]
What's the error message that you're getting, could you paste the console output?

Thanks for reporting this issue btw, it's nice to know what still needs fixing in grunt2gulp.

**Comment by fatkhanfauzi** [comment]
Here is the error that i got :

`[my@localhost mosaico]$ grunt2gulp Gruntfile.js
/home/my/.nvm/versions/node/v0.12.7/lib/node_modules/grunt2gulp/bin/grunt2gulp.js:534
        throw e;
              ^
TypeError: undefined is not a function
    at module.exports (/home/my/Workspace/mosaico/Gruntfile.js:6:9)
    at convertGruntFile (/home/my/.nvm/versions/node/v0.12.7/lib/node_modules/grunt2gulp/bin/grunt2gulp.js:505:3)
    at Object.<anonymous> (/home/my/.nvm/versions/node/v0.12.7/lib/node_modules/grunt2gulp/bin/grunt2gulp.js:517:7)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
`

Nice idea anyway to create this package.
Glad to use it.
Hope it can be improved by the time.
;)

**Comment by omouse** [comment]
which version of grunt2gulp are you running? the latest 0.0.2+ or 0.0.1?

I'm trying out grunt2gulp right now on the Gruntfile and it's complaining about installing load-grunt-tasks which is a newer feature I added in 0.0.2.

**Comment by fatkhanfauzi** [comment]
i'm using 0.2 omouse..

**Comment by omouse** [comment]
I hope this gets you a good start on converting the Gruntfile to a Gulpfile. There's a lot of cleanup to do, like combining the duplicate bowercopy tasks, and fixing all the browserify tasks because the source files are all undefined. Combining the watch tasks is also a good idea.

Here's the Gulpfile that was generated after removing loadTasks and installing load-grunt-tasks, jshint-stylish, autoprefixer-core and installing csswring.

### Gulpfile.js

```js
var gulp = require('gulp');
var rename = require('gulp-rename');


gulp.task('makeThumbs', function () {
  return gulp
    .src('[object Object]')
    .pipe(gulp.dest('main'))
  ;
});

gulp.task('combineKOTemplates', function () {
  return gulp
    .src('src/tmpl/*.tmpl.html')
    .pipe(gulp.dest('build/templates.js'))
  ;
});

gulp.task('jshint', function () {
  return gulp
    .src('Gruntfile.js,src/**/*.js')
    .pipe(jshint())
    .pipe(jshint.reporter('default'))
  ;
});

gulp.task('less', function () {
  return gulp
    .src('src/css/app_standalone.less')
    .pipe(gulp.dest('build/mosaico.css,build/mosaico-material.css'))
  ;
});

gulp.task('less', function () { // WARNING: potential duplicate task
  return gulp
    .src('src/css/app_standalone_material.less')
    .pipe(gulp.dest('build/mosaico.css,build/mosaico-material.css'))
  ;
});

gulp.task('postcss', function () {
  return gulp
    .src('build/mosaico.css')
    .pipe(gulp.dest('dist/mosaico.min.css'))
  ;
});

gulp.task('postcss', function () { // WARNING: potential duplicate task
  return gulp
    .src('build/mosaico-material.css')
    .pipe(gulp.dest('dist/mosaico-material.min.css'))
  ;
});

gulp.task('browserify', function () {
  return gulp
    .src('undefined')
    .pipe(gulp.dest(','))
  ;
});

gulp.task('browserify', function () { // WARNING: potential duplicate task
  return gulp
    .src('undefined')
    .pipe(gulp.dest(','))
  ;
});

gulp.task('browserify', function () { // WARNING: potential duplicate task
  return gulp
    .src('undefined')
    .pipe(gulp.dest(','))
  ;
});

gulp.task('browserify', function () { // WARNING: potential duplicate task
  return gulp
    .src('undefined')
    .pipe(gulp.dest(','))
  ;
});

gulp.task('exorcise', function () {
  return gulp
    .src('undefined')
    .pipe(gulp.dest(''))
  ;
});

gulp.task('watch', function () {
  gulp.watch('src/css/*.less', [ /* dependencies */ ]);
});

gulp.task('watch', function () {
  gulp.watch('src/**/*.css', [ /* dependencies */ ]);
});

gulp.task('watch', function () {
  gulp.watch('src/tmpl/*.tmpl.html', [ /* dependencies */ ]);
});

gulp.task('watch', function () {
  gulp.watch('build/mosaico.debug.js', [ /* dependencies */ ]);
});

gulp.task('watch', function () {
  gulp.watch('*.html', [ /* dependencies */ ]);
});

gulp.task('watch', function () {
  gulp.watch('dist/**/*.js', [ /* dependencies */ ]);
});

gulp.task('watch', function () {
  gulp.watch('dist/**/*.css', [ /* dependencies */ ]);
});

gulp.task('watch', function () {
  gulp.watch('src/js/**/*.js', [ /* dependencies */ ]);
});

gulp.task('express', function () {
  return gulp
    .src('[object Object]')
    .pipe(gulp.dest('dev'))
  ;
});

gulp.task('copy', function () {
  return gulp
    .src('**')
    .pipe(gulp.dest('dist/'))
  ;
});

gulp.task('bowercopy', function () {
  return gulp
    .src('knockout/dist/knockout.js')
    .pipe(gulp.dest('knockout.js,jquery.min.js,jquery.min.map,jquery-ui.min.js,jquery-ui.min.css,jquery.ui.touch-punch.min.js,knockout-jqueryui.min.js,canvas-to-blob.min.js,load-image.all.min.js,jquery.iframe-transport.js,jquery.fileupload.js,jquery.fileupload-process.js,jquery.fileupload-image.js,jquery.fileupload-validate.js,evol.colorpicker.min.css,evol.colorpicker.min.js,tinymce.min.js,themes,skins,plugins,notoregular'))
  ;
});

gulp.task('bowercopy', function () { // WARNING: potential duplicate task
  return gulp
    .src('jquery/dist/jquery.min.js')
    .pipe(gulp.dest('knockout.js,jquery.min.js,jquery.min.map,jquery-ui.min.js,jquery-ui.min.css,jquery.ui.touch-punch.min.js,knockout-jqueryui.min.js,canvas-to-blob.min.js,load-image.all.min.js,jquery.iframe-transport.js,jquery.fileupload.js,jquery.fileupload-process.js,jquery.fileupload-image.js,jquery.fileupload-validate.js,evol.colorpicker.min.css,evol.colorpicker.min.js,tinymce.min.js,themes,skins,plugins,notoregular'))
  ;
});

gulp.task('bowercopy', function () { // WARNING: potential duplicate task
  return gulp
    .src('jquery/dist/jquery.min.map')
    .pipe(gulp.dest('knockout.js,jquery.min.js,jquery.min.map,jquery-ui.min.js,jquery-ui.min.css,jquery.ui.touch-punch.min.js,knockout-jqueryui.min.js,canvas-to-blob.min.js,load-image.all.min.js,jquery.iframe-transport.js,jquery.fileupload.js,jquery.fileupload-process.js,jquery.fileupload-image.js,jquery.fileupload-validate.js,evol.colorpicker.min.css,evol.colorpicker.min.js,tinymce.min.js,themes,skins,plugins,notoregular'))
  ;
});

gulp.task('bowercopy', function () { // WARNING: potential duplicate task
  return gulp
    .src('jquery-ui/jquery-ui.min.js')
    .pipe(gulp.dest('knockout.js,jquery.min.js,jquery.min.map,jquery-ui.min.js,jquery-ui.min.css,jquery.ui.touch-punch.min.js,knockout-jqueryui.min.js,canvas-to-blob.min.js,load-image.all.min.js,jquery.iframe-transport.js,jquery.fileupload.js,jquery.fileupload-process.js,jquery.fileupload-image.js,jquery.fileupload-validate.js,evol.colorpicker.min.css,evol.colorpicker.min.js,tinymce.min.js,themes,skins,plugins,notoregular'))
  ;
});

gulp.task('bowercopy', function () { // WARNING: potential duplicate task
  return gulp
    .src('jquery-ui/themes/smoothness/jquery-ui.min.css')
    .pipe(gulp.dest('knockout.js,jquery.min.js,jquery.min.map,jquery-ui.min.js,jquery-ui.min.css,jquery.ui.touch-punch.min.js,knockout-jqueryui.min.js,canvas-to-blob.min.js,load-image.all.min.js,jquery.iframe-transport.js,jquery.fileupload.js,jquery.fileupload-process.js,jquery.fileupload-image.js,jquery.fileupload-validate.js,evol.colorpicker.min.css,evol.colorpicker.min.js,tinymce.min.js,themes,skins,plugins,notoregular'))
  ;
});

gulp.task('bowercopy', function () { // WARNING: potential duplicate task
  return gulp
    .src('jqueryui-touch-punch/jquery.ui.touch-punch.min.js')
    .pipe(gulp.dest('knockout.js,jquery.min.js,jquery.min.map,jquery-ui.min.js,jquery-ui.min.css,jquery.ui.touch-punch.min.js,knockout-jqueryui.min.js,canvas-to-blob.min.js,load-image.all.min.js,jquery.iframe-transport.js,jquery.fileupload.js,jquery.fileupload-process.js,jquery.fileupload-image.js,jquery.fileupload-validate.js,evol.colorpicker.min.css,evol.colorpicker.min.js,tinymce.min.js,themes,skins,plugins,notoregular'))
  ;
});

gulp.task('bowercopy', function () { // WARNING: potential duplicate task
  return gulp
    .src('knockout-jqueryui/dist/knockout-jqueryui.min.js')
    .pipe(gulp.dest('knockout.js,jquery.min.js,jquery.min.map,jquery-ui.min.js,jquery-ui.min.css,jquery.ui.touch-punch.min.js,knockout-jqueryui.min.js,canvas-to-blob.min.js,load-image.all.min.js,jquery.iframe-transport.js,jquery.fileupload.js,jquery.fileupload-process.js,jquery.fileupload-image.js,jquery.fileupload-validate.js,evol.colorpicker.min.css,evol.colorpicker.min.js,tinymce.min.js,themes,skins,plugins,notoregular'))
  ;
});

gulp.task('bowercopy', function () { // WARNING: potential duplicate task
  return gulp
    .src('blueimp-canvas-to-blob/js/canvas-to-blob.min.js')
    .pipe(gulp.dest('knockout.js,jquery.min.js,jquery.min.map,jquery-ui.min.js,jquery-ui.min.css,jquery.ui.touch-punch.min.js,knockout-jqueryui.min.js,canvas-to-blob.min.js,load-image.all.min.js,jquery.iframe-transport.js,jquery.fileupload.js,jquery.fileupload-process.js,jquery.fileupload-image.js,jquery.fileupload-validate.js,evol.colorpicker.min.css,evol.colorpicker.min.js,tinymce.min.js,themes,skins,plugins,notoregular'))
  ;
});

gulp.task('bowercopy', function () { // WARNING: potential duplicate task
  return gulp
    .src('blueimp-load-image/js/load-image.all.min.js')
    .pipe(gulp.dest('knockout.js,jquery.min.js,jquery.min.map,jquery-ui.min.js,jquery-ui.min.css,jquery.ui.touch-punch.min.js,knockout-jqueryui.min.js,canvas-to-blob.min.js,load-image.all.min.js,jquery.iframe-transport.js,jquery.fileupload.js,jquery.fileupload-process.js,jquery.fileupload-image.js,jquery.fileupload-validate.js,evol.colorpicker.min.css,evol.colorpicker.min.js,tinymce.min.js,themes,skins,plugins,notoregular'))
  ;
});

gulp.task('bowercopy', function () { // WARNING: potential duplicate task
  return gulp
    .src('jquery-file-upload/js/jquery.iframe-transport.js')
    .pipe(gulp.dest('knockout.js,jquery.min.js,jquery.min.map,jquery-ui.min.js,jquery-ui.min.css,jquery.ui.touch-punch.min.js,knockout-jqueryui.min.js,canvas-to-blob.min.js,load-image.all.min.js,jquery.iframe-transport.js,jquery.fileupload.js,jquery.fileupload-process.js,jquery.fileupload-image.js,jquery.fileupload-validate.js,evol.colorpicker.min.css,evol.colorpicker.min.js,tinymce.min.js,themes,skins,plugins,notoregular'))
  ;
});

gulp.task('bowercopy', function () { // WARNING: potential duplicate task
  return gulp
    .src('jquery-file-upload/js/jquery.fileupload.js')
    .pipe(gulp.dest('knockout.js,jquery.min.js,jquery.min.map,jquery-ui.min.js,jquery-ui.min.css,jquery.ui.touch-punch.min.js,knockout-jqueryui.min.js,canvas-to-blob.min.js,load-image.all.min.js,jquery.iframe-transport.js,jquery.fileupload.js,jquery.fileupload-process.js,jquery.fileupload-image.js,jquery.fileupload-validate.js,evol.colorpicker.min.css,evol.colorpicker.min.js,tinymce.min.js,themes,skins,plugins,notoregular'))
  ;
});

gulp.task('bowercopy', function () { // WARNING: potential duplicate task
  return gulp
    .src('jquery-file-upload/js/jquery.fileupload-process.js')
    .pipe(gulp.dest('knockout.js,jquery.min.js,jquery.min.map,jquery-ui.min.js,jquery-ui.min.css,jquery.ui.touch-punch.min.js,knockout-jqueryui.min.js,canvas-to-blob.min.js,load-image.all.min.js,jquery.iframe-transport.js,jquery.fileupload.js,jquery.fileupload-process.js,jquery.fileupload-image.js,jquery.fileupload-validate.js,evol.colorpicker.min.css,evol.colorpicker.min.js,tinymce.min.js,themes,skins,plugins,notoregular'))
  ;
});

gulp.task('bowercopy', function () { // WARNING: potential duplicate task
  return gulp
    .src('jquery-file-upload/js/jquery.fileupload-image.js')
    .pipe(gulp.dest('knockout.js,jquery.min.js,jquery.min.map,jquery-ui.min.js,jquery-ui.min.css,jquery.ui.touch-punch.min.js,knockout-jqueryui.min.js,canvas-to-blob.min.js,load-image.all.min.js,jquery.iframe-transport.js,jquery.fileupload.js,jquery.fileupload-process.js,jquery.fileupload-image.js,jquery.fileupload-validate.js,evol.colorpicker.min.css,evol.colorpicker.min.js,tinymce.min.js,themes,skins,plugins,notoregular'))
  ;
});

gulp.task('bowercopy', function () { // WARNING: potential duplicate task
  return gulp
    .src('jquery-file-upload/js/jquery.fileupload-validate.js')
    .pipe(gulp.dest('knockout.js,jquery.min.js,jquery.min.map,jquery-ui.min.js,jquery-ui.min.css,jquery.ui.touch-punch.min.js,knockout-jqueryui.min.js,canvas-to-blob.min.js,load-image.all.min.js,jquery.iframe-transport.js,jquery.fileupload.js,jquery.fileupload-process.js,jquery.fileupload-image.js,jquery.fileupload-validate.js,evol.colorpicker.min.css,evol.colorpicker.min.js,tinymce.min.js,themes,skins,plugins,notoregular'))
  ;
});

gulp.task('bowercopy', function () { // WARNING: potential duplicate task
  return gulp
    .src('evol-colorpicker/css/evol.colorpicker.min.css')
    .pipe(gulp.dest('knockout.js,jquery.min.js,jquery.min.map,jquery-ui.min.js,jquery-ui.min.css,jquery.ui.touch-punch.min.js,knockout-jqueryui.min.js,canvas-to-blob.min.js,load-image.all.min.js,jquery.iframe-transport.js,jquery.fileupload.js,jquery.fileupload-process.js,jquery.fileupload-image.js,jquery.fileupload-validate.js,evol.colorpicker.min.css,evol.colorpicker.min.js,tinymce.min.js,themes,skins,plugins,notoregular'))
  ;
});

gulp.task('bowercopy', function () { // WARNING: potential duplicate task
  return gulp
    .src('evol-colorpicker/js/evol.colorpicker.min.js')
    .pipe(gulp.dest('knockout.js,jquery.min.js,jquery.min.map,jquery-ui.min.js,jquery-ui.min.css,jquery.ui.touch-punch.min.js,knockout-jqueryui.min.js,canvas-to-blob.min.js,load-image.all.min.js,jquery.iframe-transport.js,jquery.fileupload.js,jquery.fileupload-process.js,jquery.fileupload-image.js,jquery.fileupload-validate.js,evol.colorpicker.min.css,evol.colorpicker.min.js,tinymce.min.js,themes,skins,plugins,notoregular'))
  ;
});

gulp.task('bowercopy', function () { // WARNING: potential duplicate task
  return gulp
    .src('tinymce/tinymce.min.js')
    .pipe(gulp.dest('knockout.js,jquery.min.js,jquery.min.map,jquery-ui.min.js,jquery-ui.min.css,jquery.ui.touch-punch.min.js,knockout-jqueryui.min.js,canvas-to-blob.min.js,load-image.all.min.js,jquery.iframe-transport.js,jquery.fileupload.js,jquery.fileupload-process.js,jquery.fileupload-image.js,jquery.fileupload-validate.js,evol.colorpicker.min.css,evol.colorpicker.min.js,tinymce.min.js,themes,skins,plugins,notoregular'))
  ;
});

gulp.task('bowercopy', function () { // WARNING: potential duplicate task
  return gulp
    .src('tinymce/themes')
    .pipe(gulp.dest('knockout.js,jquery.min.js,jquery.min.map,jquery-ui.min.js,jquery-ui.min.css,jquery.ui.touch-punch.min.js,knockout-jqueryui.min.js,canvas-to-blob.min.js,load-image.all.min.js,jquery.iframe-transport.js,jquery.fileupload.js,jquery.fileupload-process.js,jquery.fileupload-image.js,jquery.fileupload-validate.js,evol.colorpicker.min.css,evol.colorpicker.min.js,tinymce.min.js,themes,skins,plugins,notoregular'))
  ;
});

gulp.task('bowercopy', function () { // WARNING: potential duplicate task
  return gulp
    .src('tinymce/skins')
    .pipe(gulp.dest('knockout.js,jquery.min.js,jquery.min.map,jquery-ui.min.js,jquery-ui.min.css,jquery.ui.touch-punch.min.js,knockout-jqueryui.min.js,canvas-to-blob.min.js,load-image.all.min.js,jquery.iframe-transport.js,jquery.fileupload.js,jquery.fileupload-process.js,jquery.fileupload-image.js,jquery.fileupload-validate.js,evol.colorpicker.min.css,evol.colorpicker.min.js,tinymce.min.js,themes,skins,plugins,notoregular'))
  ;
});

gulp.task('bowercopy', function () { // WARNING: potential duplicate task
  return gulp
    .src('tinymce/plugins')
    .pipe(gulp.dest('knockout.js,jquery.min.js,jquery.min.map,jquery-ui.min.js,jquery-ui.min.css,jquery.ui.touch-punch.min.js,knockout-jqueryui.min.js,canvas-to-blob.min.js,load-image.all.min.js,jquery.iframe-transport.js,jquery.fileupload.js,jquery.fileupload-process.js,jquery.fileupload-image.js,jquery.fileupload-validate.js,evol.colorpicker.min.css,evol.colorpicker.min.js,tinymce.min.js,themes,skins,plugins,notoregular'))
  ;
});

gulp.task('bowercopy', function () { // WARNING: potential duplicate task
  return gulp
    .src('webfont-notosans/regular')
    .pipe(gulp.dest('knockout.js,jquery.min.js,jquery.min.map,jquery-ui.min.js,jquery-ui.min.css,jquery.ui.touch-punch.min.js,knockout-jqueryui.min.js,canvas-to-blob.min.js,load-image.all.min.js,jquery.iframe-transport.js,jquery.fileupload.js,jquery.fileupload-process.js,jquery.fileupload-image.js,jquery.fileupload-validate.js,evol.colorpicker.min.css,evol.colorpicker.min.js,tinymce.min.js,themes,skins,plugins,notoregular'))
  ;
});

gulp.task('bowercopy', function () { // WARNING: potential duplicate task
  return gulp
    .src('font-awesome/fonts/fontawesome-webfont.woff2')
    .pipe(gulp.dest('fonts/fontawesome-webfont.woff2,fonts/fontawesome-webfont.woff,fonts/fontawesome-webfont.ttf,fonts/fontawesome-webfont.svg,fonts/fontawesome-webfont.eot'))
  ;
});

gulp.task('bowercopy', function () { // WARNING: potential duplicate task
  return gulp
    .src('font-awesome/fonts/fontawesome-webfont.woff')
    .pipe(gulp.dest('fonts/fontawesome-webfont.woff2,fonts/fontawesome-webfont.woff,fonts/fontawesome-webfont.ttf,fonts/fontawesome-webfont.svg,fonts/fontawesome-webfont.eot'))
  ;
});

gulp.task('bowercopy', function () { // WARNING: potential duplicate task
  return gulp
    .src('font-awesome/fonts/fontawesome-webfont.ttf')
    .pipe(gulp.dest('fonts/fontawesome-webfont.woff2,fonts/fontawesome-webfont.woff,fonts/fontawesome-webfont.ttf,fonts/fontawesome-webfont.svg,fonts/fontawesome-webfont.eot'))
  ;
});

gulp.task('bowercopy', function () { // WARNING: potential duplicate task
  return gulp
    .src('font-awesome/fonts/fontawesome-webfont.svg')
    .pipe(gulp.dest('fonts/fontawesome-webfont.woff2,fonts/fontawesome-webfont.woff,fonts/fontawesome-webfont.ttf,fonts/fontawesome-webfont.svg,fonts/fontawesome-webfont.eot'))
  ;
});

gulp.task('bowercopy', function () { // WARNING: potential duplicate task
  return gulp
    .src('font-awesome/fonts/fontawesome-webfont.eot')
    .pipe(gulp.dest('fonts/fontawesome-webfont.woff2,fonts/fontawesome-webfont.woff,fonts/fontawesome-webfont.ttf,fonts/fontawesome-webfont.svg,fonts/fontawesome-webfont.eot'))
  ;
});

gulp.task('jasmine_node', function () {
  return gulp
    .src('src/**/*.js')
  ;
});

gulp.task('js', ["combineKOTemplates","browserify","exorcise"]);

gulp.task('css', ["less","postcss"]);

gulp.task('server', ["express","watch","express-keepalive"]);

gulp.task('build', ["bowercopy","copy","jshint","js","css"]);

gulp.task('default', ["build","server"]);

gulp.task('test', ["jasmine_node"]);


```

**Comment by fatkhanfauzi** [comment]
Cool, however the browserify is not properly formatted, but well thanks @omouse 
:+1:
