### ISSUE TITLE
grunt.file.expandMapping not supported

### ISSUE THREAD

**Issue by askucher** [omouse/grunt2gulp.js#23]
TypeError: grunt.file.expandMapping is not a function
    at makePair (/home/ubuntu/workspace/gruntfile.js:10:25)
    at module.exports (/home/ubuntu/workspace/gruntfile.js:54:12)
    at convertGruntFile (/home/ubuntu/.nvm/versions/node/v4.3.2/lib/node_modules/grunt2gulp/bin/grunt2gulp.js:505:3)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.3.2/lib/node_modules/grunt2gulp/bin/grunt2gulp.js:517:7)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)

**Comment by omouse** [comment]
@askucher how does your Gruntfile look like?
