### ISSUE TITLE
Throws exception on sample, grunt2gulp.js:534

### ISSUE THREAD

**Issue by bedge** [omouse/grunt2gulp.js#25]
I can't provide the sample I'm under NDA. I know, not helpful, sorry, but I just through I'd try it out and this is the result. Hopefully it's better than nothing.

%> grunt2gulp Gruntfile.js
/usr/local/lib/node_modules/grunt2gulp/bin/grunt2gulp.js:534
        throw e;
        ^

TypeError: Cannot use 'in' operator to search for 'src' in undefined
    at processGruntConfig (/usr/local/lib/node_modules/grunt2gulp/bin/grunt2gulp.js:223:38)
    at gruntConverter.initConfig (/usr/local/lib/node_modules/grunt2gulp/bin/grunt2gulp.js:432:9)
    at module.exports (/Users/bedge/quicklabs/geospatial-app-code/Gruntfile.js:48:9)
    at convertGruntFile (/usr/local/lib/node_modules/grunt2gulp/bin/grunt2gulp.js:505:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/grunt2gulp/bin/grunt2gulp.js:517:7)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

**Comment by omouse** [comment]
This is getting frustrating. How is it possible that a Gruntfile, which is similar to a Makefile and other build files be under an NDA?

Anyway, you can try using the node.js debugger and running the grunt2gulp.js script through it. Step through and it should give you a better idea of which line it's failing on. Without the Gruntfile I would be blindly guessing at this point and I'm guessing it's an issue in parsing the list of source files. Are you using an alternative to the `src` key in one of your objects/hashes? Maybe something like `files` or `srcs` or something?

**Comment by omouse** [comment]
@bedge it looks like an issue with readJSON; since it isn't implemented, the other files are not loaded up. I'll paste the short snippet:

    aws: grunt.file.readJSON("aws.json"),
    bootcamp: grunt.file.readJSON("bootcamp.json"),
    es: grunt.file.readJSON("es.json")

If you look at the code of grunt2gulp, readJSON is a no-op at the moment. There's an issue opened for this: https://github.com/omouse/grunt2gulp.js/issues/8

The workaround is to move the JSON from the files into the Gruntfile.js, I'll prioritize readJSON since it's pretty useful, I should at least be logging when and where it's called.

**Comment by omouse** [comment]
Closing this issue, I have two other issues open to alleviate this kind of problem.
