### ISSUE TITLE
Exception: grunt.option is not a function

### ISSUE THREAD

**Issue by ioxEU** [omouse/grunt2gulp.js#29]
Hello folks,

I just followed the documentation to be able to convert my gruntFile but when i launch the command: grunt2gulp Gulpfile.js i got an exception. Please find below the detail:

> C:\Users\XXX\AppData\Roaming\npm\node_modules\grunt2gulp\bin\grunt2gulp.js:534
>         throw e;
>         ^
> TypeError: grunt.option is not a function
>     at module.exports (C:\Users\XXX\Desktop\authoringtool\dev\node_modules\j
> it-grunt\lib\jit-grunt.js:138:29)
>     at module.exports (C:\Users\XXX\Desktop\authoringtool\dev\node_modules\j
> it-grunt\jit-grunt.js:6:13)
>     at module.exports (C:\Users\XXX\Desktop\authoringtool\dev\Gruntfile.js:1
> 3:23)
>     at convertGruntFile (C:\Users\XXX\AppData\Roaming\npm\node_modules\grunt
> 2gulp\bin\grunt2gulp.js:505:3)
>     at Object.<anonymous> (C:\Users\XXX\AppData\Roaming\npm\node_modules\gru
> nt2gulp\bin\grunt2gulp.js:517:7)
>     at Module._compile (module.js:541:32)
>     at Object.Module._extensions..js (module.js:550:10)
>     at Module.load (module.js:458:32)
>     at tryModuleLoad (module.js:417:12)
>     at Function.Module._load (module.js:409:3)

Any idea about where the issue coming from ?

Thanks in advance for help.

Valentin

**Comment by omouse** [comment]
@ioxEU hey, it would be awesome if you could post your Gruntfile or at least the snippet around line 1.

For grunt2gulp to work, I have an object which partially matches the Grunt API. It looks like I'm missing another function that is part of the API (this has happened to others with the file.readJSON function, see #8 )

**Comment by ioxEU** [comment]
Hi @omouse ,

Sure, my project is based on Angular fullstack generator.
Please find in attachment the entire Gruntfile.

Thanks for help,
[Gruntfile.zip](https://github.com/omouse/grunt2gulp.js/files/419618/Gruntfile.zip)

**Comment by refaelos** [comment]
@omouse I'd love to get this fixed as well ..

**Comment by omouse** [comment]
awesome, awesome, more debug info, will schedule some time this weekend to work on it 👍

**Comment by cristianounix** [comment]
I have the same problem.

**Comment by omouse** [comment]
@cristianounix do you have a snippet of your Gruntfile that you can paste?

**Comment by geekguy** [comment]
@omouse : I have the same problem. Looks like it's an issue with `jit-grunt`

Here is minimal gruntfile to reproduce the issue

```
'use strict';

module.exports = function (grunt) {
  require('jit-grunt')(grunt, {
    useminPrepare: 'grunt-usemin',
  });
};

```

**Comment by omouse** [comment]
@geekguy is there an equivalent for jit-grunt for gulp? One issue reported above is that grunt.option isn't defined, the other issue is that the module needs an equivalent for gulp: https://github.com/omouse/grunt2gulp.js/blob/master/bin/grunt2gulp.js#L281

**Comment by geekguy** [comment]
@omouse  - Not sure about alternative. But jit-grunt is just faster plugin loader.

We can replace that using 

```
grunt.loadNpmTasks('grunt-usemin');
```

More details - https://www.npmjs.com/package/jit-grunt
