### ISSUE TITLE
`grunt.file.readYAML` is not implemented

### ISSUE THREAD

**Issue by korya** [omouse/grunt2gulp.js#7]
The script failed for me with the following error:

```sh
$ node aa.js Gruntfile.js > Gulp.js
/Users/korya/dev/test-app/Gruntfile.js:11
    config: grunt.file.readYAML('config.yml'),
                       ^
TypeError: undefined is not a function
    at module.exports (/Users/korya/dev/test-app/Gruntfile.js:11:24)
    at convertGruntFile (/Users/korya/dev/test-app/aa.js:441:3)
    at Object.<anonymous> (/Users/korya/dev/test-app/aa.js:450:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

The relevant part of my Gruntfile:

```javascript

...
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    config: grunt.file.readYAML('config.yml'),
 ...
```

**Comment by omouse** [comment]
Need to implement a readYAML on the file api: https://github.com/omouse/grunt2gulp.js/blob/master/bin/grunt2gulp.js#L366

Not sure what the equivalent functionality would be for gulp.

Should it be something like this?

    // equivalent of readJSON('package.json')
    var pkg = require('package.json');
    // equivalent of readYAML('config.yml')
    var yaml = require('js-yaml');
    try {
        var config = yaml.safeLoad(fs.readFileSync('config.yml', 'utf8'));
    } catch(e) {
        console.log(e);
    }

I'm using js-yaml as a guide but that adds a dependency to your gulp file: https://www.npmjs.com/package/js-yaml

**Comment by omouse** [comment]
@korya is it possible for you to paste your Gruntfile?

**Comment by korya** [comment]
Sorry, I'm afraid I cannot provide it as is. But I can provide a relevant part of it.
`readYAML()` is used to load a `config.yml` file (containing a build configuration) into `config` object; later that `config` is used in tasks definitions and more.

The main reasons why we use YAML instead of JSON are: comment support and references (circular objects).

Anyway, the relevant part of our Gruntfile is:

```js
/* global module:false */
module.exports = function(grunt) {
  'use strict';

  // Project configuration.
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    config: grunt.file.readYAML('config.yml'),

    clean: {
      all: ['<%= config.build %>/'],
    },

   ... Other task definitions ...
  });

  grunt.loadNpmTasks('grunt-contrib-clean');
  ... Load other tasks ...

  grunt.registerTask('default', [ ... ]);
};
```
